### ISSUE TITLE
useless_peer  response from bootstrap node

### ISSUE THREAD

**Issue by fastchain** [ethereum/pydevp2p#51]
Hello, 
 I'm launching  (from latest dev branch)

`python app.py
`

With bootstrap node 

enode://a979fb575495b8d6db44f750317d0f4622bf4c2aa3365d6af7c284339968eef29b69ad0dce72a4d8db5ebb4968de0e3bec910127f134779fbcb0cb6d3331163c@52.16.188.185:30303

And then I get

```
DEBUG:p2p.peermgr       connecting random node=<Node(a979fb57)>
DEBUG:p2p.peermgr       connecting address=('52.16.188.185', 30303)
DEBUG:p2p.peermgr       connecting to connection=<socket fileno=8 sock=10.254.70.202:44202 peer=52.16.188.185:30303 timeout=2.0>
DEBUG:p2p.peer  peer init peer=<Peer('52.16.188.185', 30303) >
DEBUG:p2p.ctxmonitor    init 
DEBUG:p2p.peer  registering protocol peer=<Peer('52.16.188.185', 30303) > protocol=p2p
DEBUG:protocol  starting proto=<P2PProtocol <Peer('52.16.188.185', 30303) >>
DEBUG:p2p.peermgr       created new peer peer=<Peer('52.16.188.185', 30303) > fno=8
DEBUG:p2p.peermgr       peer started peer=<Peer('52.16.188.185', 30303) > fno=8
DEBUG:p2p.peer  peer starting main loop 
DEBUG:p2p.peer  wrote data ts=1484124215.17 size=307
DEBUG:p2p.peer  read data ts=1484124215.53 size=243
DEBUG:p2p.peer  wrote data ts=1484124215.57 size=176
DEBUG:p2p.peer  read data ts=1484124215.57 size=143
DEBUG:p2p.peer  recv packet cmd=hello protocol=p2p orig_cmd_id=0
DEBUG:p2p.protocol      receive_hello peer=<Peer('52.16.188.185', 30303) > version=4
INFO:p2p.peer   received hello client_version=Geth/v1.5.4-stable-b70acf3c/linux/go1.7.3 version=4 capabilities=(('eth', 63), ('eth', 62))
DEBUG:p2p.peermgr       hello_received peer=<Peer('52.16.188.185', 30303) > num_peers=1
DEBUG:p2p.peer  connecting services services=[<PeerManager at 0x7f4a456d7730>]
DEBUG:p2p.ctxmonitor    started monitor=<ConnectionMonitor at 0x7f4a456d7a50>
DEBUG:p2p.ctxmonitor    pinging monitor=<ConnectionMonitor at 0x7f4a456d7a50>
DEBUG:p2p.peer  send packet peer=<Peer('52.16.188.185', 30303) Geth/v1.5.4-stable-b70acf3c> cmd=ping protcol=p2p
DEBUG:p2p.peer  wrote data ts=1484124215.58 size=64
DEBUG:p2p.peer  read data ts=1484124215.84 size=33
DEBUG:p2p.peer  read data ts=1484124215.84 size=15
DEBUG:p2p.peer  read data ts=1484124215.84 size=16
DEBUG:p2p.peer  recv packet cmd=disconnect protocol=p2p orig_cmd_id=1
DEBUG:p2p.protocol      receive_disconnect peer=<Peer('52.16.188.185', 30303) Geth/v1.5.4-stable-b70acf3c> reason=useless_peer

```

It looks like node drops me woth useless_peer  status. 
What is wrong?
How to debug?

Thank you!

**Comment by ulope** [comment]
Hi!

Nothing is wrong. This repository only contains the pure ethereum p2p protocol library implementation. You're running without any actual functionality. So the other peer will (in this case Geth) reject you because you're not an ethereum node.

Please use the [Python ethereum client](https://github.com/ethereum/pyethapp/)

**Comment by fastchain** [comment]
Thank you for your reply @ulope !
As far as I understand p2p it's  just abstraction level for DHT node discovery (Kademlia), so It is not obvious, why pure p2p is not compatible with p2p from ethereum client.   Could you please shortly explain wht the difference?  Thank you.

**Comment by ulope** [comment]
It's compatible but you were connecting with an Geth ethereum node which requires it's peers to have the 'eth' capability (which are not implemented here since this is only the protocol library). Peers that don't announce this capabilities are rejected by Geth.

You could run two devp2p nodes and they would happily handshake and then do nothing beyond that.
